name: 'Knative func build'
description: 'GitHub Action to build and publish a container image using the Knative func plugin'
author: 'Thomas Vitale'
branding:
  icon: 'command'
  color: 'blue'
inputs:
  registry_url:
    description: 'The URL for the container registry where to publish the image'
    required: true
  registry_username:
    description: 'The username to authenticate with the container registry'
    required: true
  registry_token:
    description: 'The token to authenticate with the container registry'
    required: true
  func_path:
    description: 'The path where the func.yaml is located'
    required: true
  func_name:
    description: 'The name of the function'
    required: true
  func_version:
    description: 'The version of the function'
    required: false
    default: latest
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.registry_url }}
    - ${{ inputs.registry_username }}
    - ${{ inputs.registry_token }}
    - ${{ inputs.func_path }}
    - ${{ inputs.func_name }}
    - ${{ inputs.func_version }}
