name: Release 
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag prefix'
        default: 'rc'
        required: true

jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Compute version 
        id: prep
        run: |
          VERSION="${{ github.event.inputs.tag }}-${GITHUB_SHA::8}"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\//}
          fi
          echo ::set-output name=BUILD_DATE::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=VERSION::${VERSION}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: qwpto
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/qwpto/kn-func-build:${{ steps.prep.outputs.VERSION }}
            ghcr.io/qwpto/kn-func-build:latest
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
